### ISSUE TITLE
Meeting agenda

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [NodeLagos/first-meetup-planning#2]
We'll need to decide the following:

- Start time 
- How long the meeting should last
- Sequence of activities
- Timing for each activity

**Comment by segun-adeleye** [comment]
I guess some of the points highlighted here (https://github.com/NodeLagos/first-meetup-planning/issues/1#issuecomment-393448344) are related to this

**Comment by OpesanyaAdebayo** [comment]
Yea...I wanted us to isolate the discussion for the agenda from the one for the speakers. I thought that if we focus on just deciding the agenda separately, it will help in deciding who we're reaching out to and how many volunteers we're looking to take.
But I think I can just close this issue and we can all discuss it at #1
